import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';
import { Resource } from '../../resources/entities/resource.entity';
import { ReservationStatus } from '../enums/reservation-status.enum';

@Entity('reservation')
export class Reservation {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Index()
  @Column({ name: 'resource_id', type: 'uuid' })
  resourceId: string;

  @ManyToOne(() => Resource, { onDelete: 'RESTRICT' })
  @JoinColumn({ name: 'resource_id' })
  resource: Resource;

  /** References Better Auth's "user" table, whose id is text, not uuid. */
  @Column({ name: 'user_id', type: 'text' })
  userId: string;

  @Column({ type: 'varchar', length: 160 })
  title: string;

  @Column({ name: 'start_at', type: 'timestamptz' })
  startAt: Date;

  @Column({ name: 'end_at', type: 'timestamptz' })
  endAt: Date;

  /**
   * Generated by PostgreSQL as tstzrange(start_at, end_at, '[)').
   *
   * Read-only here on purpose: the database owns it, which is what stops it
   * drifting from the two columns it derives from. It is also the column the
   * reservation_no_overlap constraint is built on.
   */
  @Column({ type: 'tstzrange', insert: false, update: false, select: false })
  readonly period: string;

  @Column({ type: 'enum', enum: ReservationStatus, default: ReservationStatus.CONFIRMED })
  status: ReservationStatus;

  @Column({ type: 'int', nullable: true })
  attendees: number | null;

  @Column({ type: 'text', nullable: true })
  notes: string | null;

  @Column({ name: 'cancelled_at', type: 'timestamptz', nullable: true })
  cancelledAt: Date | null;

  @Column({ name: 'cancelled_by', type: 'text', nullable: true })
  cancelledBy: string | null;

  @Column({ name: 'cancellation_reason', type: 'varchar', length: 300, nullable: true })
  cancellationReason: string | null;

  /**
   * Makes a retried request safe.
   *
   * Backed by a partial unique index on (user_id, idempotency_key), so the
   * many rows without a key do not collide with one another.
   */
  @Column({ name: 'idempotency_key', type: 'varchar', length: 80, nullable: true })
  idempotencyKey: string | null;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt: Date;
}
