import {
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { Resource } from './resource.entity';

/**
 * A period in which a resource cannot be booked: maintenance, a holiday, a
 * breakdown. Subtracts availability without being a reservation.
 */
@Entity('resource_block')
export class ResourceBlock {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'resource_id', type: 'uuid' })
  resourceId: string;

  @ManyToOne(() => Resource, (resource) => resource.blocks, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'resource_id' })
  resource: Resource;

  @Column({ name: 'start_at', type: 'timestamptz' })
  startAt: Date;

  @Column({ name: 'end_at', type: 'timestamptz' })
  endAt: Date;

  /**
   * Generated by PostgreSQL as tstzrange(start_at, end_at, '[)').
   *
   * Declared read-only so the ORM never tries to write it: the database owns
   * the value, which is what stops it drifting out of sync with the two
   * columns it derives from.
   */
  @Column({ type: 'tstzrange', insert: false, update: false, select: false })
  readonly period: string;

  @Column({ type: 'varchar', length: 300 })
  reason: string;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt: Date;
}
